# Generated by Django 2.0.1 on 2019-06-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('object_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(max_length=20, verbose_name='昵称')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='地址')),
                ('message', models.CharField(default='', max_length=200, verbose_name='留言信息')),
            ],
            options={
                'verbose_name': '用户留言信息',
                'verbose_name_plural': '用户留言信息',
                'db_table': 'user_massage',
                'ordering': ['object_id'],
            },
        ),
    ]
